// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ChainCommand","status":true,"description":"Everyone loves quicktime events.","parameters":{"---Configuration---":"","Valid Keys":"up down left right ok cancel","Default Switch ID":"1","Default Time Given":"360","Time Per Key":"30","Exit Pause Time":"45","---Sound Effects----":"","Keypress SFX":"Cursor2","Keypress Volume":"100","Keypress Pitch":"100","Keypress Pan":"0","Success SFX":"Heal3","Success Volume":"100","Success Pitch":"100","Success Pan":"0","Error SFX":"Blind","Error Volume":"100","Error Pitch":"100","Error Pan":"0","---Timer Bar----":"","Bar BG X Position":"285","Bar BG Y Position":"245","Meter X Shift":"5","Meter Y Shift":"5","Meter Width":"236","Meter Height":"7","---Buttons----":"","Button X Shift":"0","Button Y Shift":"0","Button Width":"31","Button Height":"31","Button Spacing":"15","---Cursor----":"","Cursor X Shift":"5","Cursor Y Shift":"40","":""}}
];
